version: "3.8"
services:
  backend:
    container_name: app-backend
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/workspace:cached
      - ./backend:/app
      - /app/node_modules
    command: sleep infinity
    depends_on:
      - database
  database:
    container_name: app-db
    image: mongo:4.2
    ports:
      - "27017:27017"
  client: 
    container_name: app-frontend 
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - .:/workspace:cached
      - ./client:/app
      - /app/node_modules
    command: sleep infinity
    depends_on: 
      - database 
      - backend 